[package]
name = "pallet-bridge-out"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[package.metadata.cargo-machete]
ignored = ["scale-info"]

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"], default-features = false }
scale-info = { workspace = true, features = ["derive"], default-features = false }
sp-std = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }

[features]
default = ["std"]
std = [
  "parity-scale-codec/std",
  "scale-info/std",
  "sp-std/std",
  "sp-core/std",
  "sp-runtime/std",
  "frame-support/std",
  "frame-system/std",
]
