[package]
name = "pallet-governance-api"
authors = ["Commune Nucleus Team"]
version = "1.0.0"
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]

[dependencies]
sp-runtime.workspace = true
